services:
  vps-benchmark:
    image: vps-benchmark:latest
    restart: unless-stopped
    ports:
      - "12345:12345"
    volumes:
      - ./data:/app/data
      - ./statics/test_results:/app/statics/test_results
      - ./statics/reports:/app/statics/reports